receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024
  resource:
    attributes:
      - key: service.name
        value: drinksync-backend
        action: upsert

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: drinksync-logs
    traces_index: drinksync-traces
    metrics_index: drinksync-metrics
  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [elasticsearch, logging]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [elasticsearch, logging]
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [elasticsearch, logging]
